---

- name: Install ambari-server
  yum: name=ambari-server state=installed

- name: Ensure ambari-server is stopped
  shell: ambari-server stop

- name: Configure ambari-server
  shell: ambari-server setup -j {{ java_home }} -s > /tmp/ambari-install-output executable=/bin/bash
  environment:
    JAVA_HOME: "{{ java_home }}"

- name : Check if ambari-server is installed
  wait_for : path=/tmp/ambari-install-output search_regex="completed successfully"

- name : Start ambari server and enabled at reboot
  shell : ambari-server start

- name : Check if ambari-server is up
  wait_for : host=127.0.0.1 port=8080 delay=10
