---

- name: Check if ambari-server is installed
  yum:
    list=ambari-server
  register: pkg

- import_tasks: install.yml
  when: pkg.results|selectattr("yumstate", "match", "installed")|list|length == 0

- import_tasks: upgrade.yml
  when: pkg.results|selectattr("yumstate", "match", "installed")|list|length != 0