---

ambari_server: admin

# ambari API vars
stack_name: HDP
stack_version: 2.2

# hdp versions
hdp_version: 2.2.9.0
hdp_utils_version: 1.1.0.20

# blueprint & cluster creation
blueprint_name: hadoop
cluster_name: default
cluster_type: single

# kerberos
kerberos_server_realm_name: HDP.LOCAL
kerberos_server_kadmin_pass: admin
kerberos_server_kadmin_user: admin
kerberos_server: admin

# hadoop configuration
default_password: hadoop

hdp_repo_version_name: HDP-{{ hdp_version }}
hdp_utils_repo_version_name : HDP-UTILS-{{ hdp_utils_version }}

hdp_baseurl: http://public-repo-1.hortonworks.com/HDP/centos{{ ansible_distribution_major_version }}/2.x/updates/{{ hdp_version }}/
hdp_utils_baseurl: http://public-repo-1.hortonworks.com/HDP-UTILS-{{ hdp_utils_version }}/repos/centos{{ ansible_distribution_major_version }}/

local_repo: False

#hdp_baseurl: http://repo.{{ domain_name }}/hdp/centos{{ ansible_distribution_major_version }}/HDP-{{ hdp_version }}
#hdp_utils_baseurl : http://repo.{{ domain_name }}/hdp_utils/centos{{ ansible_distribution_major_version }}/HDP-UTILS-{{ hdp_utils_version }}

