---
  - name : Copy stack definition
    template: src=blueprint.json.j2 dest=/tmp/blueprint.json

  - name : Copy cluster definition
    template: src=create-cluster.json.j2 dest=/tmp/create-cluster.json

  - name : Copy HDP repo definition
    template: src=create-hdp-repo.json.j2 dest=/tmp/create-hdp-repo.json

  - name : Copy HDP Utils definition
    template: src=create-hdp-utils-repo.json.j2 dest=/tmp/create-hdp-utils-repo.json

  - name: POST stack definition
    command: "curl --silent --show-error -H \"X-Requested-By: ambari\" -X POST -d '@/tmp/blueprint.json' -u admin:admin http://admin:8080/api/v1/blueprints/{{ blueprint_name }}"

  - name: PUT HDP repo definition
    command: "curl --silent --show-error -H \"X-Requested-By: ambari\" -X PUT -d '@/tmp/create-hdp-repo.json' -u admin:admin  http://admin:8080/api/v1/stacks/{{ stack_name }}/versions/{{ stack_version }}/operating_systems/redhat{{ ansible_distribution_major_version }}/repositories/{{ hdp_repo_version_name }}"
    when: False

  - name: PUT HDP Utils repo definition
    command: "curl --silent --show-error -H \"X-Requested-By: ambari\" -X PUT -d '@/tmp/create-hdp-utils-repo.json' -u admin:admin  http://admin:8080/api/v1/stacks/{{ stack_name }}/versions/{{ stack_version }}/operating_systems/redhat{{ ansible_distribution_major_version }}/repositories/{{ hdp_utils_repo_version_name }}"
    when: False

  - name: POST cluster definition
    command: "curl --silent --show-error -H \"X-Requested-By: ambari\" -X POST -d '@/tmp/create-cluster.json' -u admin:admin http://admin:8080/api/v1/clusters/{{ cluster_name }}"
    register: output

#  - name: POST stack definition
#    uri:
#      url: http://admin:8080/api/v1/blueprints/{{ blueprint_name }}
#      method: POST
#      user: admin
#      password: admin
#      body: "{{ lookup('template', 'blueprint.json.j2') }}"
#      force_basic_auth: yes
#      body_format: raw
#      headers:
#        X-Requested-By: "ambari"
#
#  - name: PUT HDP repo definition
#    uri:
#      url: http://admin:8080/api/v1/stacks/{{ stack_name }}/versions/{{ stack_version }}/operating_systems/redhat{{ ansible_distribution_major_version }}/repositories/{{ hdp_repo_version_name }}
#      method: PUT
#      user: admin
#      password: admin
#      body: "{{ lookup('template', 'create-hdp-repo.json') }}"
#      headers:
#        X-Requested-By: "ambari"
#      body_format: json
#    when: False
#
#  - name: PUT HDP Utils repo definition
#    uri:
#      url: http://admin:8080/api/v1/stacks/{{ stack_name }}/versions/{{ stack_version }}/operating_systems/redhat{{ ansible_distribution_major_version }}/repositories/{{ hdp_utils_repo_version_name }}
#      method: PUT
#      user: admin
#      password: admin
#      body: "{{ lookup('template', 'create-hdp-utils-repo.json') }}"
#      headers:
#        X-Requested-By: "ambari"
#      body_format: json
#    when: False
#
#  - name: POST cluster definition
#    uri:
#      url: http://admin:8080/api/v1/clusters/{{ cluster_name }}
#      method: POST
#      user: admin
#      password: admin
#      body: "{{ lookup('template', 'create-cluster.json') }}"
#      headers:
#        X-Requested-By: "ambari"
#      body_format: json