---

- name: Copy no_proxy
  copy: src=no_proxy.sh dest=/tmp/no_proxy.sh mode=0755
  when: False

- name: Apply on (no_proxy) ambari template
  shell: /tmp/no_proxy.sh
  when: False
  
- include: blueprint.yml
  when: True

- include: kerberos.yml
  when: False

- include: upgrade.yml
  when: False