---

- name: Copy new stack definition
  template: src=upgrade/register-hdp-stack.json.j2 dest=/tmp/register-hdp-stack.json

- name: Register the stack
  command: "curl -H \"X-Requested-By: ambari\" -u admin:admin -X POST -d '@/tmp/register-hdp-stack.json' http://{{ ambari_server }}:8080/api/v1/stacks/{{ stack_name }}/versions/{{ stack_version }}/repository_versions"
  when: False

- name: Copy new stack installation
  template: src=upgrade/install-hdp-stack.json.j2 dest=/tmp/install-hdp-stack.json

- name: Install the stack
  command: "curl -H \"X-Requested-By: ambari\" -u admin:admin -X POST -d '@/tmp/install-hdp-stack.json' http://{{ ambari_server }}:8080/api/v1/clusters/{{ cluster_name }}/stack_versions"
  when: False

  # wait until finished

  # services checks to do

- name: Copy new stack upgrade
  template: src=upgrade/upgrade-hdp-stack.json.j2 dest=/tmp/upgrade-hdp-stack.json

- name: Upgrade the stack
  command: "curl -H \"X-Requested-By: ambari\" -u admin:admin -X POST -d '@/tmp/upgrade-hdp-stack.json' http://{{ ambari_server }}:8080/api/v1/clusters/{{ cluster_name }}/upgrades"
  when: True

  # wait until finished with HOLDING task to complete 

