---

- name: Install Ambari repo.
  get_url: url="{{ ambari_repo_url }}" dest=/etc/yum.repos.d/ambari.repo force=yes
    
- name: Install HDP repo.
  get_url: url="{{ hdp_repo_url }}" dest=/etc/yum.repos.d/hdp.repo force=yes

- name: Install HDP utils repo.
  get_url: url="{{ hdp_utils_repo_url }}" dest=/etc/yum.repos.d/hdp_utils.repo force=yes

- name: Import Ambari Repo GPG key.
  rpm_key:
    key: "{{ ambari_repo_gpg_key_url }}"
    state: present

- name: Install createrepo
  yum: name={{ item }} state=latest
  with_items:
   - createrepo
   - yum-utils
  
- name: Install httpd
  yum: name={{ item }} state=present
  with_items:
   - httpd

- name: Httpd service state
  service: name=httpd state=started enabled=yes
 
- name: Create ambari local repo directory
  file: dest=/var/www/html/ambari/centos{{ ansible_distribution_major_version }}/{{ ambari_repo_version_name }} state=directory mode=0755

- name: Reposync with remote ambari repo
  command: "{{ item }}"
  with_items:
   - reposync -r {{ ambari_repo_version_name }} -p /var/www/html/ambari/centos{{ ansible_distribution_major_version }}
   - createrepo /var/www/html/ambari/centos{{ ansible_distribution_major_version }}/{{ ambari_repo_version_name }}

- name: Create HDP local repo directory
  file: dest=/var/www/html/hdp/centos{{ ansible_distribution_major_version }}/{{ hdp_repo_version_name }} state=directory mode=0755
  
- name: Reposync with remote hdp repo
  command: "{{ item }}"
  with_items:
    - reposync -r {{ hdp_repo_version_name }} -p /var/www/html/hdp/centos{{ ansible_distribution_major_version }}
    - createrepo /var/www/html/hdp/centos{{ ansible_distribution_major_version }}/{{ hdp_repo_version_name }}

- name: Create HDP util local repo directory
  file: dest=/var/www/html/hdp/centos{{ ansible_distribution_major_version }}//{{ hdp_utils_repo_version_name }} state=directory mode=0755
  
- name: Reposync with remote hdp-util repo
  command: "{{ item }}"
  with_items:
   - reposync -r {{ hdp_utils_repo_version_name }} -p /var/www/html/hdp/centos{{ ansible_distribution_major_version }}
   - createrepo /var/www/html/hdp/centos{{ ansible_distribution_major_version }}/{{ hdp_utils_repo_version_name }}