---

#http://docs.hortonworks.com/HDPDocuments/Ambari-2.2.0.0/bk_Installing_HDP_AMB/content/_hdp_stack_repositories.html
ambari_repo_url: "http://public-repo-1.hortonworks.com/ambari/centos{{ ansible_distribution_major_version }}/2.x/updates/2.2.0.0/ambari.repo"
ambari_repo_gpg_key_url: "http://s3.amazonaws.com/dev.hortonworks.com/ambari/centos{{ ansible_distribution_major_version }}/RPM-GPG-KEY/RPM-GPG-KEY-Jenkins"

hdp_repo_url: "http://public-repo-1.hortonworks.com/HDP/centos{{ ansible_distribution_major_version }}/2.x/updates/2.3.4.0/hdp.repo"
hdp_util_repo_url: "http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.21/repos/centos{{ ansible_distribution_major_version }}/hdp-util.repo"
java_home: "/etc/alternatives/java_sdk"